from typing import List, Optional
from pydantic import BaseModel, Field, field_validator
from pydantic_models.citation import Citation

class StructuredAnswer(BaseModel):
    """Encapsulates the structured output generated by the LLM, containing the response and citations."""
    answer: str = Field(..., description="The comprehensive, synthesis answer based ONLY on the provided context.")
    citations: List[Citation] = Field(default_factory=list, description="List of source citations supporting the answer.")
    confidence_score: float = Field(..., description="Confidence score from 0.0 to 1.0 reflecting confidence based on context availability.")

    @field_validator("confidence_score")
    @classmethod
    def validate_confidence_score(cls, v: float) -> float:
        if not (0.0 <= v <= 1.0):
            raise ValueError("Confidence score must be between 0.0 and 1.0")
        return v

class RetrievedChunk(BaseModel):
    """Represents a retrieved document chunk with vector metadata and similarity score."""
    content: str = Field(..., description="The text content of the chunk.")
    score: float = Field(..., description="Similarity or relevance score.")
    title: str = Field(..., description="The title of the research paper.")
    page: int = Field(..., description="The page number.")
    chunk_id: str = Field(..., description="The chunk identifier.")
    source: str = Field(..., description="The source file path or name.")
    author: Optional[str] = Field(None, description="The authors of the research paper.")

class RetrieverOutput(BaseModel):
    """Summary of a retrieval execution."""
    query: str = Field(..., description="The query used for retrieval.")
    retrieved_chunks: List[RetrievedChunk] = Field(..., description="The list of chunks retrieved.")
    latency_ms: float = Field(..., description="The time taken in milliseconds to retrieve chunks.")

class EvaluationOutput(BaseModel):
    """RAG Evaluation metrics conforming to RAGAS and DeepEval standards."""
    faithfulness: float = Field(..., description="Faithfulness / truthfulness of the answer (0.0 to 1.0).")
    context_precision: float = Field(..., description="Relevance of retrieved context to query.")
    context_recall: float = Field(..., description="Completeness of retrieved context with respect to ground truth.")
    hallucination_score: float = Field(..., description="Indication of hallucinations in the answer (lower is better).")
    answer_relevancy: float = Field(..., description="Relevancy of answer to the user query.")
    semantic_similarity: float = Field(..., description="Semantic alignment between answer and ground truth.")
    retrieval_accuracy: float = Field(..., description="Accuracy of vector retrieval stages.")
    verdict: str = Field(..., description="Overall evaluation verdict or summary.")
